services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: "your_telegram_bot_token_here"
      ALLOWED_CHAT_ID: "your_allowed_chat_id_here"
      DB_HOST: "your_db_host_here"
      DB_PORT: "your_db_port_here"
      DB_DATABASE: "your_db_name_here"
      DB_USERNAME: "your_db_user_here"
      DB_PASS: "your_db_password_here"
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: python bot.py